FROM python:alpine
ENV REDIS_HOST=redis
ADD python /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD ["python", "app.py"]

#  docker build -f Dockerfile-python -t abhishekjaiswal/python-app .