apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-webapp
  name: {{ .Release.Name }}-{{ .Chart.Name }}-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-webapp
  type: LoadBalancer
status:
  loadBalancer: {}