apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  type: ClusterIP