apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}